name: Run transcripts-extraction Pipline
env:
    GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write
  repository-projects: write
  packages: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cncf-youtube-channel-summarizer/requirements.txt

    - name: Extract YouTube Video Information.
      run: | 
           python cncf-youtube-channel-summarizer/extract_youtube_videos_info.py  

    - name: Upload transcript
      uses: actions/upload-artifact@v4
      with:
        name: CNCF_video_information_with_date.json
        path: cncf-youtube-channel-summarizer/data/CNCF_video_information_with_date.json

    - name: Commit Change for "CNCF_video_information_with_date.json"
      run: |
          git config --global user.email "dependabot[bot]@users.noreply.github.com" 
          git config --global user.name "dependabot[bot]"
          git add cncf-youtube-channel-summarizer/data/CNCF_video_information_with_date.json || exit 0
          git commit -m "Add Video Information" --signoff || exit 0
          git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
